### PR TITLE
Customizations

### PR DESCRIPTION
**Pull request by adroitandroid**
1.  Following attributes and their handling added:

-      <attr name="gravity">
            <enum name="left" value="0" />
            <enum name="right" value="1" />
            <enum name="center" value="2" />
            <enum name="staggered" value="3" /> 
       </attr>

-      <attr name="typeface" format="string" />

-      <attr name="allCaps" format="boolean" />
-      <attr name="textSize" format="dimension" />
-      <attr name="minHorizontalSpacing" format="dimension" />
-      <attr name="verticalSpacing" format="dimension" />
2. build() method can be used to re-initialize layout
3. update() method added, can be used to update labels
4. README updated

### CODE REVIEW

**Comment by fiskurgit** [comment]
Will catch up with this over the next few days and get it merged - cheers

**Comment by adroitandroid** [comment]
nice, thanks 👍  I was thinking I'll need to maintain my own version of it as you seemed inactive

**Comment by fiskurgit** [comment]
k, merged the pull - people seem to be using this thing so will try and find time to ramp up development.

**Comment by adroitandroid** [comment]
Yes please do, 10 people have already starred my fork of the repo, within 4-5 days, so it must be useful. Why I chose your implementation over others is because other material implementations either don't exist in entirety or are hard to find.

**Comment by fiskurgit** [comment]
Have closed off a few other bugs - I'll rewrite the Chip class soon too, I have no idea why I didn't just subclass ToggleButton...

**Comment by adroitandroid** [comment]
Checkout https://developer.android.com/reference/android/widget/CheckedTextView.html

**Pull request merged**
